name: CI

on: 
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

permissions: 
  checks: write
  pull-requests: write

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Typing
        run: mypy --ignore-missing-imports dundie
      - name: Loop for style errors
        run: pflake8
      - name: Check for importing style
        run: isort --profile=black -m 3 --check --diff dundie tests integration
      - name: Look for auto format erros
        run: black --check --diff dundie tests integration

  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Run tests
        run: pytest -v --junitxml=test-results.xml --forked
      - name: publish junit results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json